# (1.2) NumPy Exercises from Simple to Difficult

Das folgende Notebook sollen Ihnen ein selbstständiges Erarbeiten der wichtigsten Funktionen und Konzepte der Numpy-Bibliothek in Python ermöglichen. Diese Bibliothek ist ein zentraler Bestandteil vieler Machine Learning Frameworks wie zum Beispiel Scikit-Learn. Die Bibliothek erlaubt das effiziente Rechnen mit wesentlichen Datenstrukturen des Maschinellen Lernens wie Vektoren und Matrizen und stellt darüber hinaus Funktionen der linearen Algebra und Analysis zur Verfügung. NumPy ist zwingende Voraussetzung für das sogenannte *Scientific Computing* in Python.

Die folgenden Übungen sind zu einem großen Teil der folgenden Ressource entnommen/entlehnt:
https://www.machinelearningplus.com/python/101-numpy-exercises-python/.

Auch im Rahmen des Kurses wird NumPy eine wesentliche Rolle spielen. Während die wichtigsten Elemente der Bibliothek und deren Benutzung im Rahmen des Maschinelle Lernens im Verlauf des Kurses nach und nach eingeführt werden, soll Ihnen dieses Notebook zunächst einen Überblick über die Fülle der Möglichkeiten verschaffen, den Sie sich komplett selbst erarbeiten können.

Es ist nicht zwingend erforderlich, alle Aufgaben dieses Notebooks unmittelbar zu lösen. Vielmehr soll es Ihnen erste Übungsansätze bieten, Ihnen als Inspirationsquelle für spätere Aufgaben dienen, sowie Ihnen eine erste Selbsteinschätzung ermöglichen.

Dazu sind die einzelnen Aufgaben farbkodiert bzw. symbolkodiert. Die zwei Skalen drücken einerseits die Schwierigkeit und andererseits die Wichtigkeit der Aufgabe für die Kursinhalte aus:

### Schwierigkeit:

<span style="color:green; font-size:2em">(o)</span> - Leicht: diese Aufgabe ist eher leicht und sollte, wenn Sie mit Ihren Kenntnissen noch am Anfang sind, ihr Fokus sein. Die Aufgabe kann als leicht eingestuft sein, obwohl sie Kenntnisse aus vorherigen (leichten) Aufgaben voraussetzt.

<span style="color:orange; font-size:2em">(oo)</span> - Mittel: diese Aufgabe ist etwas schwerer, weil sie zum Beispiel das Zusammenwirken mehrerer Funktionen oder die Bedienung einer schwierigeren Funktion erfordert, weil Sie selbstständig nach den passenden Funktionen recherchieren müssen oder weil die Aufgabe bislang unbekannte Konzepte einführt.

<span style="color:red; font-size:2em">(ooo)</span> - Schwer: diese Aufgabe ist schwerer, weil sie zum Beispiel das Zusammenwirken mehrerer komplexer Funktionen erfordert, unterspezifiziert ist, zusätzliche Recherchen und Transferdenken erfordert, oder ein Ansatz nicht unmittelbar erkennbar ist.

### Relevanz:

<span style="font-size:2em">&#x1F4D7;</span> - Wichtig: diese Aufgabe ist eher wichtig, weil die Benutzung der gelernten Inhalte entweder sehr oft zum Tragen kommt oder die folgenden Inhalte darauf aufbauen. Zur Erreichung des Lernziel sind diese Aufgaben entscheidend.

<span style="font-size:2em">&#x1F4D9;</span> - Weiterführend: diese Aufgabe vermittelt eher weiterführende Inhalte. Das kann heißen, dass keine weiteren Inhalte darauf aufbauen oder dass es in diesen Fällen auch alternative Lösungswege gibt. Dennoch können diese Aufgaben für das Lernziel des jeweiligen Kursabschnitts relevant sein.

<span style="font-size:2em">&#x1F4D8;</span> - Optional: diese Aufgabe vermittelt weiterführende Inhalte, die sich ignorieren lassen, ohne dass Sie dabei das Lernziel des Kurses oder Kursinhalts verpassen.

### Learntools

Neben der Kodierung der Aufgaben ermöglicht es Ihnen die von kaggle-learn inspirierte Mikro-Lernumgebung `learntools` unabhängig vom Rest des Kurses zu üben. Durch Import des `learntools` Moduls wie unten angegeben gibt es für jede Aufgabe zusätzliche Hinweise, Lösungen oder Lösungsvorschläge und Kontrollen. Für eine gegebene Aufgabe, zum Beispiel `q1`, lassen sich diese mit den folgenden Befehlen aufrufen:

```python
q1.hint()
q1.check()
q1.solution()
```

Durch `q1.hint()` wird ein zusätzlicher Hinweis gegeben. Das kann ein Hinweis auf eine relevante Funktion oder ein Vorschlag für einen Ansatz sein. Nicht alle Aufgaben habe solche Hinweise, und viele haben mehrere Hinweise, die Sie sich nacheinander anzeigen lassen sollten, indem sie zum Beispiel `q1.hint(2)` ausführen.

Durch `q1.check()` wird Ihre Lösung kontrolliert. Dies erfordert, dass Sie die Variablen der Lösung auf genau die Weise benannt und strukturiert haben wie in der Aufgabe angegeben. Im Einzelnen kann die Kontrolle fehlschlagen, obwohl Ihre Lösung richtig ist, weil nicht alle möglichen Lösungswege antizipiert werden, Ihre Lösungsstruktur leicht abweicht oder es zu anderen Rundungsfehlern kam. Außerdem funktioniert diese Funktionalität immer nur genau im Abschnitt der Aufgabe. Durch Ausführen verschiedener Zellen aus vorherigen Aufgaben, die gleich benannte Variablen verwenden, kann es zu Konflikten kommen. Führen Sie in diesem Fall die Zellen der Aufgabe erneut aus oder starten Sie sogar das Notebook neu.

Durch `q1.solution()` wird Ihnen die Lösung oder ein oder mehrere Lösungsvorschläge angezeigt. Ihre Lösung kann natürlich davon abweichen. Generell werden dort besonders konzise Lösungswege bevorzugt. Denken Sie daran, dass sich allein durch das Lesen von Lösungen gewöhnlich kein Lernerfolg einstellt.

In [6]:
import sys
import os

# Optional
# learntools_path = "../" # "path/to/learntools/folder"
# sys.path.append(learntools_path)

from learntools.core import binder; binder.bind(globals())
from learntools.exercises.numpy_exercise import *
print("Setup complete.")

Setup complete.


In [7]:
import numpy as np

# Q1: 1D Array <span style="color:green; font-size:1em">(o)</span>  &#x1F4D7;

Create a 1D array of numbers from 0 to 9

Erzeugen Sie ein 1D Array mit den Zahlen von 0 bis 9.

In [12]:
out = np.arange(10)

In [16]:
# q1.check()
# q1.hint()
# q1.solution()

# Q2: Boolean Array <span style="color:green; font-size:1em">(o)</span>  &#x1F4D7;

Create a 3×3 numpy array of all `True`’s.

Erzeugen Sie ein 3x3 Numpy Array, das überall den Wert `True` enthält.

In [16]:
out = ... # TODO

# Q3: Selecting Values on Condition <span style="color:green; font-size:1em">(o)</span>  &#x1F4D7;

Extract all odd numbers from `arr`.

Extrahieren Sie all ungeraden Zahlen aus dem Array `arr`.

```python
>>> out
np.array([1, 3, 5, 7, 9])
```

In [34]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

out = ... # TODO

# Q4: Replacing Values on Condition <span style="color:green; font-size:1em">(o)</span>  &#x1F4D7;

Replace all odd numbers in `arr` with the value $-1$.

Ersetzen Sie alle ungeraden Zahlen im Array `arr` mit dem Wert $-1$.

```python
>>> arr
np.array([0, -1, 2, -1, 4, -1, 6, -1, 8, -1])
```

In [30]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# TODO
arr[arr % 2 == 1] = -1

# Q5: Reshaping <span style="color:green; font-size:1em">(o)</span>  &#x1F4D7;

Convert a 1D array to a 2D array with 2 rows. Make sure that one row is filled completely
before moving on to the next row (as opposed to filling column by column).

Wandeln Sie ein 1D Array in ein 2D Array mit 2 Zeilen um. Stellen Sie sicher, dass das entstehende
Array zeilenweise und nicht spaltenweise mit den Werten des 1D Arrays aufgefüllt wird.

In [11]:
arr = np.arange(10)
out = ... # TODO

# Q6: Stacking Arrays Vertically <span style="color:orange; font-size:1em">(oo)</span>  &#x1F4D7;

Stack arrays `a` and `b` "vertically".

Fügen Sie die Arrays `a` und `b` "vertikal" zusammen.

```python
>>> a
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

>>> b
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

>>> out
array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])
```

In [22]:
a = np.arange(10).reshape(2,-1)
b = np.ones((2, 5))

out = ...  # TODO

# Q7: Stacking Horizontally <span style="color:orange; font-size:1em">(oo)</span>  &#x1F4D7;

Stack arrays `a` and `b` "horizontally".

Fügen Sie die Arrays `a` und `b` "horizontal" zusammen.

```python
>>> a
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

>>> b
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

>>> out
array([[0., 1., 2., 3., 4., 1., 1., 1., 1., 1.],
       [5., 6., 7., 8., 9., 1., 1., 1., 1., 1.]])
```

In [15]:
a = np.arange(10).reshape(2,-1)
b = np.ones((2, 5))

out = ...  # TODO

# Q8: Tiling and Repeating I <span style="color:orange; font-size:1em">(oo)</span>  &#x1F4D9;

Create the following pattern without hardcoding. Use only numpy functions and the below input array `a`.

Erzeugen Sie das folgende Muster nur durch Benutzung des Arrays `a` und entsprechender Numpy-Funktionen.


```python
>>> out
np.array([1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [17]:
a = np.array([1,2,3])

out = ...  # TODO

# Q9: Tiling and Repeating II <span style="color:orange; font-size:1em">(oo)</span>  &#x1F4D9;

Create the following pattern without hardcoding. Use only numpy functions and the below input array `a`.

Erzeugen Sie das folgende Muster nur durch Benutzung des Arrays `a` und entsprechender Numpy-Funktionen.


```python
np.array([
    [1, 2, 3],
    [1, 2, 3],
    [1, 2, 3]
])
```

In [19]:
a = np.array([1,2,3])

out = ...  # TODO

# Q10: Common Sub-Array Between Two Arrays <span style="color:green; font-size:1em">(o)</span>  &#x1F4D7;

Get the matching sub-array between `a` and `b`.

Finden und extrahieren Sie das Sub-Array, in dem `a` und `b` übereinstimmen.

In [21]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

out = ...  # TODO

# Q11: Counting matching entries <span style="color:green; font-size:1em">(o)</span>  &#x1F4D7;

Count the matches between the equal-length arrays `a` and `b`.

Zählen Sie die Übereinstimmungen zwischen den gleichlangen Arrays `a` und `b`.

In [23]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

n_matches = ...  # TODO

# Q12: Proportion of matching entries <span style="color:green; font-size:1em">(o)</span>  &#x1F4D7;

Compute the propoertion of matching entries between the equal-length arrays `a` and `b`.

Berechnen Sie den Prozentsatz der Übereinstimmungen zwischen den gleichlangen Arrays `a` und `b`.

In [25]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

prop_matches = ...  # TODO

# Q13: Finding the positions of matching entries. <span style="color:orange; font-size:1em">(oo)</span>  &#x1F4D9;

Get the positions where elements of arrays `a` and `b` match.

Finden Sie die Positionen, an denen die Arrays `a` und `b` übereinstimmen.

In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

matching_positions = ...  # TODO

# Q14: Most frequent value <span style="color:orange; font-size:1em">(oo)</span>  &#x1F4D9;

Find the most frequent value in array `a`.

Finden Sie den am häufigsten vorkommenden Wert im Array `a`.

In [29]:
a = np.array([1,3,2,1,0,0,1,2,0,0,3,3,0,3,2])

most_frequent = ... # TODO


# Q15: Getting items in range <span style="color:green; font-size:1em">(o)</span>  &#x1F4D9;

Get all items in array `a` that lie between $5$ and $10$ (including).

Finden Sie alle Einträge in Array `a` die zwischen $5$ und $10$ (einschließlich) liegen.

In [31]:
a = np.array([0, 5, 3, 7, 8, 7, 1, 4, 15, 12, 0, 2, 3, 5, 9, 6, 1, 1])

out = ... # TODO

# Q16: Swapping columns <span style="color:orange; font-size:1em">(oo)</span>  &#x1F4D8;

Swap columns 1 and 2 in the array `arr`.

Vertauschen Sie die 1. und 2. Spalte des Arrays `arr`.

In [34]:
arr = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8]
])

out = ... # TODO

# Q17: Swapping rows <span style="color:orange; font-size:1em">(oo)</span>  &#x1F4D8;

Swap rows 1 and 2 in the array `arr`.

Vertauschen Sie die 1. und 2. Reihe des Arrays `arr`.

In [36]:
arr = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8]
])

out = ... # TODO

# Q18: Reversing the order of items <span style="color:orange; font-size:1em">(oo)</span>  &#x1F4D9;

Reverse the elements in the array `arr`.

Drehen Sie die Reihenfolge der Elemente in Array `arr` um.

In [38]:
# Input
arr = np.array([12, 33, 2, 3, 5, 6, 8, 10, 11, 0, 11, 1])

out = ...  # TODO

# Q19: Reversing the order of columns <span style="color:orange; font-size:1em">(oo)</span>  &#x1F4D9;

Reverse the rows in the 2D array `arr`, or, phrased alternatively, reverse the elements in each column.

Drehen Sie die Reihenfolge der Reihen in Array `arr` um. Anders gesagt, drehen Sie in jeder Spalte die Reihenfolge der Elemente um.

In [8]:
arr = np.arange(12).reshape(3, 4)

out = ...  # TODO

# Q20: Reversing the order of rows <span style="color:orange; font-size:1em">(oo)</span>  &#x1F4D9;

Reverse the columns in the 2D array `arr`, or, phrased alternatively, reverse the elements in each row.

Drehen Sie die Reihenfolge der Spalten in Array `arr` um. Anders gesagt, drehen Sie in jeder Reihe die Reihenfolge der Elemente um.

In [42]:
arr = np.arange(12).reshape(3, 4)

out = ...  # TODO

# Q21: Creating arrays I <span style="color:green; font-size:1em">(o)</span>  &#x1F4D7;

Create an array of all $2$'s with length $100$.

Erzeugen Sie ein Array, das nur $2$en als Einträge hat und die Länge $100$ besitzt.

In [44]:
twos_arr = ...  # TODO

# Q22: Creating arrays II <span style="color:orange; font-size:1em">(oo)</span>  &#x1F4D9;

Create a 2D array of shape $5x3$ to contain random decimal numbers between $5$ and $10$.

Erzeugen Sie ein 2D Array mit der Shape $5x3$, dass zufällige Dezimalzahlen zwischen $5$ und $10$ enthält.

In [46]:
# Do not change this if you want to verify the solution.
np.random.seed(18)

# TODO
rand_arr = ...

# Q23: Printing I <span style="color:green; font-size:1em">(o)</span>  &#x1F4D8;

Print or show only 3 decimal places of the numpy array `rand_arr`. Make sure to read the solution for upcoming questions.

Stellen Sie das Array `rand_arr` im Output so dar, dass Dezimalzahlen nur bis drei Stellen hinter dem Komma angezeigt werden. Lassen Sie sich danach in jedem die Lösung anzeigen.

In [48]:
# Do not change this if you want to verify the solution.
np.random.seed(18)

rand_arr = np.random.random((5,3))

# TODO
# ...

# Q24: Printing II <span style="color:green; font-size:1em">(o)</span>  &#x1F4D8;

Pretty print `rand_arr` by suppressing the scientific notation (like `1e10`).

Finden Sie eine lesbare Darstellung von `rand_arr`, die auf Notationen wie `1e10` verzichtet.

In [50]:
# Do not change this if you want to verify the solution.
np.random.seed(22)

rand_arr = np.random.random([3,3])/1e4

# Observe scientific notation for this array
print(rand_arr)

# TODO
# ...

[[2.08460537e-05 4.81681062e-05 4.20538035e-05]
 [8.59181999e-05 1.71161554e-05 3.38863961e-05]
 [2.70532833e-05 6.91041350e-05 2.20404517e-05]]


# Q25: Printing III <span style="color:green; font-size:1em">(o)</span>  &#x1F4D8;

Limit the number of items printed in python numpy array a to a maximum of $10$ elements (default is $1000$).

Begrenzen Sie die maximale Größe des Arrays, das durch Print-Outs noch vollständig dargestellt wird, auf $10$ (der Default ist $1000$).

In [52]:
# Should be truncated
a = np.arange(11)

# Should be displayed fully
b = np.arange(10)

# TODO
# ...

# Q26: Printing IV <span style="color:green; font-size:1em">(o)</span>  &#x1F4D8;

Print the full numpy array `a` without truncating.

Stellen Sie das Array `a` vollständig dar, das heißt ohne Begrenzung des Print-Outs.

In [54]:
a = np.arange(20000).reshape(100, 200)

# TODO
# ...

# Q27: Import Iris Dataset <span style="color:green; font-size:1em">(o)</span>  &#x1F4D7;

Import the iris dataset through `sklearn.datasets.load_iris`.

Importieren Sie den Iris-Datensatz durch `sklearn.datasets.load_iris`.

In [56]:
from sklearn.datasets import load_iris

iris = ...  # TODO

# Q28: Loading Iris data matrix <span style="color:green; font-size:1em">(o)</span>  &#x1F4D7;

Extract the data matrix from the dataset of the previous question. It is a 2D array or otherwise called matrix with a number of rows that each represent a sample and a number of columns that each represent a feature.

Extrahieren Sie die Datenmatrix aus dem Datensatz der vorherigen Aufgabe. Es handelt sich um ein 2D Array, auch Matrix genannt, mit einer Menge an Reihen, die jeweils einen Datenpunkt repräsentieren und einer Menge an Spalten, die jeweils ein Merkmal repräsentieren.

In [58]:
X = ...  # TODO

# Q29: Loading the Iris target vector <span style="color:green; font-size:1em">(o)</span>  &#x1F4D7;

Extract the target vector from the Iris dataset from before. The target vector is a vector with as many entries as there are samples in the data matrix. The target vector is a "code" meaning the numbers in the vector represent different classes. There should be $3$ classes coded in the numbers ${0, 1, 2}$. Thus each sample is assigned a class.

Extrahieren Sie den Vektor der Zielvariablen aus dem Iris-Datensatz von zuvor. Der Vektor der Zielvariablen hat genau so viele Einträge wie es Datenpunkte in der Datenmatrix gibt. Er ist "kodiert", das heißt die angegebenen Zahlen repräsentieren verschiedene Klassen. Es sollte $3$ Klassen geben, die durch die Zahlen ${0, 1, 2}$ dargestellt sind. Jedem Datenpunkt ist somit eine Klasse zugeordnet.

In [60]:
y = ...  # TODO

# Q30: Mean, median and standard deviation I <span style="color:green; font-size:1em">(o)</span>  &#x1F4D7;

Find the mean, median, standard deviation of the Iris dataset's *sepal length (cm)* (1st column).

Berechnen Sie den Durchschnittswert, Median und die Standardabweichung des Features *sepal length (cm)* aus dem Iris-Datensatz (erste Spalte).

In [62]:
mean = ...  # TODO
median = ...  # TODO
sd = ...  # TODLösungswegeO

# Q31: Mean, median and standard deviation II <span style="color:orange; font-size:1em">(oo)</span>  &#x1F4D7;

Find the mean, median, standard deviation of the Iris dataset's *petal width (cm)*. Find out the correct column yourself.

Berechnen Sie den Durchschnittswert, Median und die Standardabweichung des Features *petal width (cm)* aus dem Iris-Datensatz. Identifizieren Sie selbstständig die korrekte Spalte.

In [64]:
mean = ...  # TODO
median = ...  # TODO
sd = ...  # TODO

# Q32: Mean, median and standard deviation III <span style="color:orange; font-size:1em">(oo)</span>  &#x1F4D7;

Find the mean, median, standard deviation of all the features in the Iris dataset und collect them each in a vector with length equal to the number of features.

Berechnen Sie den Durchschnittswert, Median und die Standardabweichung aller Features aus dem Iris-Datensatz und speichern Sie die Ergebnisse jeweils in einem Vektor mit der Länge der Anzahl der Features.

In [66]:
means = ...  # TODO
medians = ...  # TODO
sds = ...  # TODO

# Q33: Standardizing I <span style="color:orange; font-size:1em">(oo)</span>  &#x1F4D9;

Compute a new matrix in which all features are shifted such that they have mean $0$.

Erzeugen Sie eine neue Matrix, sodass alle Features den Durchschnittswert $0$ haben (aber die relativen Abstände der Werte gleich bleiben).

In [68]:
X_new = ...  # TODO

# Q34: Standardizing II <span style="color:orange; font-size:1em">(oo)</span>  &#x1F4D9;

Compute a new matrix in which all features are shifted such that they have mean $0$ and scaled such that they have standard devation $1$.

Erzeugen Sie eine neue Matrix, sodass alle Features den Durchschnittswert $0$ und die Standardabweichung $1$ haben (aber die relativen Abstände der Werte gleich bleiben).

In [70]:
X_new = ...  # TODO

# Q35: Selecting rows I <span style="color:green; font-size:1em">(o)</span>  &#x1F4D7;

Extract all samples of the data matrix `X` that have the class *versicolor*.

Extrahieren Sie alle Datenpunkte der Klasse *versicolor*.

In [72]:
X_sub = ...  # TODO

# Q36: Selecting rows II <span style="color:orange; font-size:1em">(oo)</span>  &#x1F4D7;

Extract all samples of the data matrix `X` that have the class *setosa* and whose *petal length (cm)* is larger than $4,5$.

Extrahieren Sie alle Datenpunkte der Klasse *setosa* für die *petal length (cm)* größer als $4.5$ ist.

In [74]:
X_sub = ...  # TODO

# Q37: Percentiles <span style="color:red; font-size:1em">(ooo)</span>  &#x1F4D8;

Find the $5$th and $95$th percentile of *sepal length (cm)* in the Iris dataset.

Berechnen Sie das $5.$ und $95.$ Perzentil des Features *sepal length (cm)* im Iris Datensatz.

In [76]:
percentiles = ...  # TODO: store both percentiles in an array

# Q38: Correlation coefficient <span style="color:orange; font-size:1em">(oo)</span>  &#x1F4D9;

Find the correlation coefficient between the features *sepal length (cm)* and *sepal width (cm)* in the Iris dataset.

Berechnen Sie den Korrelationskoeffizienten zwischen den Features *sepal length (cm)* und *sepal width (cm)* im Iris Datensatz.

In [78]:
corr = ...  # TODO

# Q39: Counting and unique values <span style="color:orange; font-size:1em">(oo)</span>  &#x1F4D9;

Find the unique values and the count of each unique value in the target vector of the Iris dataset.

Finden Sie alle möglichen Werte der Zielvariablen im Iris Datensatz und wie oft diese Werte jeweils auftreten.

In [80]:
unique = ...  # TODO: vector of all unique values
counts = ...  # TODO: vector of how often these unique values appear

# Q40: Binning  <span style="color:red; font-size:1em">(ooo)</span>  &#x1F4D8;

Bin the *petal length (cm)* of the Iris dataset and assign the string values *small/medium/large* to the binned values in the following way ($x_3$ is the variable expressing the *petal length (cm)*). Save the resulting string values in a vector.

Discretisieren Sie die *petal length (cm)* des Iris Datensatzes und weisen Sie den diskreten Werten die Werte *small/medium/large* auf die unten angegebene Weise zu ($x_3$ soll das Merkmal *petal length (cm)* darstellen. Speichern Sie die neuen Werte in einem Vektor.

$0 \leq x_3 < 2 \quad \rightarrow \quad \text{small}$

$2 \leq x_3 < 5 \quad \rightarrow \quad \text{medium}$

$5 \leq x_3 < \infty \quad \rightarrow \quad \text{large}$


In [88]:
x_string = ...  # TODO

# Q41: Feature Engineering <span style="color:orange; font-size:1em">(oo)</span>  &#x1F4D9;

Create a new feature for the *petal area (cm$^2$)* and add it to the data matrix (feature engineering). The area should be computed as *petal area (cm$^2$) = petal width (cm) x petal length (cm)*.

Erzeugen Sie ein neues Feature *petal area (cm$^2$)* und fügen Sie es der Datenmatrix `X` hinzu. Das neue Feature soll auf folgende Weise berechnet werden: *petal area (cm$^2$) = petal width (cm) x petal length (cm)*

In [87]:
petal_area = ...  # TODO
X_new = ...  # TODO

# Q42: Splitting datasets I <span style="color:green; font-size:1em">(o)</span>  &#x1F4D7;

Split the data matrix `X` such that the first $100$ samples are assigned to a new matrix `X1` and the final $50$ samples are assigned to a new matrix `X2`. Do the same for the target vector `y`.

Teilen Sie die Datenmatrix `X`, sodass die ersten $100$ Datenpunkte einer neuen Matrix `X1` und die letzten $50$ Datenpunkte einer Matrix `X2` zugewiesen werden. Wiederholen Sie den Prozess für den Vektor der Zielvariablen `y`.


In [89]:
X1 = ...  # TODO
X2 = ...  # TODO

y1 = ...  # TODO
y2 = ...  # TODO


# Q43: Splitting datasets II <span style="color:red; font-size:1em">(ooo)</span>  &#x1F4D7;

Split the data matrix `X` randomly assigning $100$ samples to a new matrix `X1` and $50$ samples to a new matrix `X2`. Do the same for the target vector `y`, leaving the correspondence between samples and the target variable intact. `X` should not be changed.

Teilen Sie die Datenmatrix `X` zufällig sodass $100$ Datenpunkte einer neuen Matrix `X1` und $50$ Datenpunkte einer Matrix `X2` zugewiesen werden. Wiederholen Sie den Prozess für den Vektor der Zielvariablen `y`, wobei die Beziehung zwischen Datenpunkten und Zielvariablen intakt bleiben soll. `X` soll nicht verändert werden.

In [91]:
X1 = ...  # TODO
X2 = ...  # TODO

y1 = ...  # TODO
y2 = ...  # TODO

# Q44: Grouping and selecting <span style="color:orange; font-size:1em">(oo)</span>  &#x1F4D8;

Find the second largest value of the feature *petal length (cm)* of species *setosa*.

Finden Sie den zweitgrößten Wert des Features *petal length (cm)* der Spezies *setosa*.

In [93]:
value = ...  # TODO

# Q45: Sorting I <span style="color:orange; font-size:1em">(oo)</span>  &#x1F4D9;

Sort the rows of the Iris data matrix `X` based on the feature *petal width (cm)* in **ascending** order.

Sortieren Sie die Reihen der Datenmatrix `X` **aufsteigend** auf Grundlage des Features *petal width (cm)*.

In [95]:
X_sorted = ...  # TODO

# Q46: Sorting II <span style="color:orange; font-size:1em">(oo)</span>  &#x1F4D9;

Sort the rows of the Iris data matrix `X` based on the feature *petal width (cm)* in **descending** order.

Sortieren Sie die Reihen der Datenmatrix `X` **absteigend** auf Grundlage des Features *petal width (cm)*.

In [97]:
X_sorted = ...  # TODO

# Q47: Matrix multiplication I <span style="color:green; font-size:1em">(o)</span>  &#x1F4D7;

Compute different matrix products of matrices `A` und `B`: $C = A \cdot B$ and $D = B \cdot A$.

Berechnen Sie das Matrixprodukt der Matrizen `A` und `B`: $C = A \cdot B$ und $D = B \cdot A$.

In [99]:
A = np.array([
    [0, 1, -1, 1],
    [1, 2, 1, 3],
])

B = np.array([
    [0, -1],
    [-1, 2],
    [3, 1],
    [0, 1]
])

C = ...  # TODO
D = ...  # TODO

# Q48: Matrix multiplication II <span style="color:red; font-size:1em">(ooo)</span>  &#x1F4D8;

Find a Matrix $\mathbf{A}$ such that when multiplying this matrix with a vector $\mathbf{x} = (1, 2, 3)$ from the left, i.e. $\mathbf{x}' = \mathbf{A} \cdot \mathbf{x}$, the elements of the vector are reordered in the following way $\mathbf{x}' = (2, 3, 1)$.

Finden Sie eine Matrix $\mathbf{A}$ sodass die Multiplikation von links dieser Matrix mit dem Vektor $\mathbf{x} = (1, 2, 3)$, das heißt $\mathbf{x}' = \mathbf{A} \cdot \mathbf{x}$, dafür sorgt, dass die Elemente des Vektors in folgender Weise umsortiert werden $\mathbf{x}' = (2, 3, 1)$.

In [101]:
x = np.array([1, 2, 3])

A = ...  # TODO

# Q49: Matrix multiplication III <span style="color:orange; font-size:1em">(oo)</span>  &#x1F4D7;

Compute the following quantity for the first sample of the Iris dataset: *value = sepal length (cm) + 2 x sepal width (cm) - petal length (cm) + 0.5 x petal width (cm).*

Berechnen Sie die folgende Größe für den ersten Datenpunkt des Iris Datensatzes: *value = sepal length (cm) + 2 x sepal width (cm) - petal length (cm) + 0.5 x petal width (cm).*

In [103]:
value = ...  # TODO

# Q50: Matrix multiplication IV <span style="color:red; font-size:1em">(ooo)</span>  &#x1F4D7;

Compute the following quantity for all samples of the Iris dataset: *value = sepal length (cm) + 2 x sepal width (cm) - petal length (cm) + 0.5 x petal width (cm)*. Store them in a single vector.

Berechnen Sie die folgende Größe für alle Datenpunkte des Iris Datensatzes: *value = sepal length (cm) + 2 x sepal width (cm) - petal length (cm) + 0.5 x petal width (cm)*. Speichern Sie die Ergebnisse in einem Vektor. 

In [105]:
values = ...  # TODO

# Q51: Distances I <span style="color:green; font-size:1em">(o)</span>  &#x1F4D7;

Compute the Euclidean distance between two arrays `a` and `b`.

Berechnen Sie die euklidische Distanz zwischen den den zwei Arrays `a` und `b`.

In [107]:
# Input
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

dist = ...  # TODO

# Q52: Distances II <span style="color:red; font-size:1em">(ooo)</span>  &#x1F4D9;

Compute the Euclidean distance between every sample in the Iris data matrix `X` and the mean sample (as a reminder see **Q32**). Store the result in a vector.

Berechnen Sie jeweils die euklidische Distanz zwischen allen Datenpunkten in der Iris Datenmatrix und dem durchschnittlichen Datenpunkt (als Erinnering siehe **Q32**). Speichern Sie die Distanzen in einem Vektor.

In [109]:
mean = ...  # TODO
dists = ...  # TODO

# Q53: Clipping <span style="color:green; font-size:1em">(o)</span>  &#x1F4D8;

Replace all values greater than $30$ with $30$ and all values less than $10$ by $10$ in the array `a`.

Ersetzen Sie alle Werte größer als $30$ mit $30$ und alle Werte kleiner als $10$ mit $10$ im Array `a`.

In [111]:
np.random.seed(5)
a = np.random.uniform(1, 50, 20)

out = ...  # TODO

# Q54: Top-$K$ Values <span style="color:orange; font-size:1em">(oo)</span>  &#x1F4D9;

Get the positions of the top $5$ maximum values in a given array `a` in order.

Finden Sie die Positionen der $5$ maximalen Werte im Array `a` in der entsprechenden Reihenfolge.

In [114]:
# Input
np.random.seed(5)
a = np.random.uniform(1, 50, 20)

top5 = ...  # TODO

# Q55: Reshaping II <span style="color:green; font-size:1em">(o)</span>  &#x1F4D7;

Convert the 2D array `arr2d` into a "flat" 1D array, such that all the rows of the original matrix are concatenated.

Wandeln Sie das 2D Array `arr2d` in ein "flaches" 1D array um, sodass die Reihen der ursprünglichen Matrix hintereinander geschrieben werden.

In [116]:
arr2d = np.array([
    [0, 1, 2, 1],
    [1, -1, 1, 3],
    [0, -2, 4, 1]
])

arr = ...  # TODO

# Q56: Reshaping III <span style="color:orange; font-size:1em">(oo)</span>  &#x1F4D7;

Convert the 3D array `arr3d` into a 2D array containing the same elements and with the same length along the first axis.

Wandeln Sie das 3D Array `arr3d` in ein 2D Array um, das die gleichen Elemente enthält und gleich lang entlang der ersten Achse ist.

In [118]:
# Do not change the seed if you want to check the solution
np.random.seed(4)
arr3d = np.random.normal(size=(100, 4, 4))

arr2d = ...  # TODO

# Q57: Reshaping IV <span style="color:red; font-size:1em">(ooo)</span>  &#x1F4D7;

Assume that the 1D array `arr` contains the pixel intensities of $50$ images each with a resolution of $8$x$8$ pixels. The first $64$ elements in `arr` should be considered the pixels of the first image, the following $64$ elements the pixels of the next image etc. Convert the array `arr` into a 3D array with the length $50$ along the first axis. Then get the $35$th image as an $8$x$8$ 2D array.

Nehmen Sie an, dass das 1D Array `arr` die Pixelintensitäten von $50$ Bildern mit einer Auflösung von $8$x$8$ Pixeln enthält. Die ersten $64$ Elemente in `arr` sollen das erste Bild darstellen und die folgenden $64$ Elemente das nächste Bild usw. Wandeln Sie das 1D Array `arr` in ein 3D Array um, dass entlang der ersten Achse die Länge $50$ hat. Speichern Sie dann das $35.$ Bild als ein $8$x$8$ 2D Array.

In [120]:
np.random.seed(7)
arr = np.random.uniform(0, 1, size=3200)

arr3d = ...  # TODO
image35 = ...  # TODO

# Q58: Finding the maximum I <span style="color:green; font-size:1em">(o)</span>  &#x1F4D7;

Find the position of the maximal value in the array `a`.

Finden Sie die Position des Maximums im Array `a`.

In [122]:
# Do not change the seed if you want to check the solution
np.random.seed(3)
a = np.random.normal(size=(100))

position = ...  # TODO

# Q59: Finding the maximum II <span style="color:red; font-size:1em">(ooo)</span>  &#x1F4D7;

Find the position of the maximal value in the 2D array `A`. The position has two coordinates - save them in a tuple of length $2$.

Finden Sie die Position des Maximums im Array `A`. Die Position hat zwei Koordinates - speichern Sie diese in einem Tuple der Länge $2$.

In [125]:
# Do not change the seed if you want to check the solution
np.random.seed(3)
A = np.random.normal(size=(100, 100))

position = ...  # TODO: save this as a tuple

# Q60: Computing the maximum <span style="color:orange; font-size:1em">(oo)</span>  &#x1F4D7;

Compute the maximum for each row in the given 2D array `A`. Store the results in a vector.

Berechnen Sie das Maximum für jede Reihe des 2D Arrays `A`. Speichern Sie das Ergebnis in einem Vektor.

In [127]:
# Do not change the seed if you want to check the solution
np.random.seed(3)
A = np.random.randint(1, 10, [5, 3])

maximums = ...  # TODO

# Q61: Computing the range <span style="color:orange; font-size:1em">(oo)</span>  &#x1F4D9;

Compute the range for each row in the given 2D array `A`, i.e. the absolute difference between the maximum and minimum. Store the results in a vector.

Berechnen Sie die Spanne für jede Reihe des 2D Arrays `A`, das heißt die absolute Differenz zwischen dem Maximum und dem Minimum. Speichern Sie das Ergebnis in einem Vektor.

In [132]:
# Do not change the seed if you want to check the solution
np.random.seed(3)
A = np.random.normal(size=(10, 20))

ranges = ...  # TODO

# Q62: Checking equality of arrays <span style="color:orange; font-size:1em">(oo)</span>  &#x1F4D9;

Check if the arrays `A` and `B` are exactly equal and if they are equal up to rounding errors.

Überprüfen Sie, ob die Arrays `A` und `B` exakt gleich sind und bis auf Rundungsfehler gleich sind.

In [134]:
np.random.seed(5)
A = np.random.uniform(0, 1, size=(100, 100))
B = A + 1e-15 * np.random.uniform(0, 1, size=(100, 100))

exactly_equal = ...  # TODO
approx_equal = ...  # TODO